"""add boolean field

Revision ID: 222958023381
Revises: 779bda296659
Create Date: 2021-04-25 15:11:38.512936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222958023381'
down_revision = '779bda296659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('answers', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'answers')
    # ### end Alembic commands ###
