"""add boolean field

Revision ID: 42832034c921
Revises: 222958023381
Create Date: 2021-04-25 15:17:38.496097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42832034c921'
down_revision = '222958023381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('answers_work', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'answers_work')
    # ### end Alembic commands ###
