"""add boolean field

Revision ID: 779bda296659
Revises: 807d0a493fdb
Create Date: 2021-04-25 14:55:06.642467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779bda296659'
down_revision = '807d0a493fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'public')
    # ### end Alembic commands ###
