"""Add eco column

Revision ID: 807d0a493fdb
Revises: bcce360710f5
Create Date: 2021-04-24 15:37:01.691773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807d0a493fdb'
down_revision = 'bcce360710f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ecological', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ecological')
    # ### end Alembic commands ###
